version: "3.9"

services:
  nginx:
    build:
      context: ./nginx
    container_name: web-nginx-boilerplate
    working_dir: /web/frontend
    ports:
      - 80:80
    networks:
      - web

networks:
  web:
    name: web